name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Check resx files and manifest
      shell: pwsh
      run: ./tools/Build-Manifest.ps1 -Check

    - name: get-version-from-dnn-manifest
      uses: valadas/get-version-from-dnn-manifest@b2f479d682015f2c22cd506b4a42e90574fe42e8 # v1.0.1
      id: version

    - name: Zip Release
      run: cd Resources && zip -r $FILENAME.zip *
      env:
        FILENAME: Dnn_Platform_${{ github.event.repository.name }}_${{ steps.version.outputs.versionString }}

    - name: Create Release
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      with:
        artifacts: Resources/*.zip
        body: DNN Platform ${{ github.event.repository.name }} version ${{ steps.version.outputs.versionString }}
        draft: true
        immutableCreate: true
        tag: v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
        token: ${{ secrets.GITHUB_TOKEN }}
