name: Validate
on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - 'release/**'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check resx files and manifest
        shell: pwsh
        run: ./tools/Build-Manifest.ps1 -Check
